### ISSUE TITLE
Mindsphere Token Authentication Failure

### ISSUE THREAD

**Issue by gibinjoe** [mindsphere/mindconnect-nodejs#346]
I have the mindconnect node pushing data to mindsphere on a SIMATIC LiveTwin edge device.  The device is used intermittently - couple of times every month.  Recently, when I tried to run the device, I get token authentication error on the mindconnect node.  My understanding is that new token is retrieved some time before the expiry.  How can I configure the node to retrieve the token if it is activated after the expiry?

**Comment by sn0wcat** [comment]
The agent hasn’t called MindSphere APIs for a long time
If your agent is calling MindSphere APIs only occasionally the authentication secrets might expire. In order to prevent that the Node-RED has an automatic keep alive feature which renews the client secrets even if no data is sent.  If your secret is expired you will have to onboard the agent again.
